mysql.go

Rewrite "FOR SHARE" clause to "LOCK IN SHARE MODE" for MySQL version 5.x and MariaDB
This PR is related to https://github.com/go-gorm/gorm/issues/3666#issuecomment-714415658
For example in MySQL 5.7:
```
DB.Clauses(clause.Locking{
Strength: "SHARE",
}).Find(&users)
// SELECT * FROM `users` LOCK IN SHARE MODE
```

Rewrite "FOR SHARE" Clause for MySQL 5.x and MariaDB

---

mysql.go
mysql_test.go

escape backticks in QuoteTo
according to https://dev.mysql.com/doc/refman/5.6/en/identifiers.html

feat: escape backticks

---

migrator.go
mysql.go

The detailed implementation of the code should be as simple and readable as possible. Don't have too many boundary judgments in the code, logic like if...else, while ensuring readability in the main function, you must carry out a reasonable abstraction, don't pay too much attention to the realization, I think the abstraction ability and layering Design ability, these two are very important. This piece suggests that the host should look at some of the design ideas in Worse is better.
https://github.com/go-gorm/mysql/pull/38

optimize DataTypeOf func and other code optimize for mysql package

---

migrator.go

feat: implement CurrentDatabase for mysql

---

migrator.go

feat: impl GetTables

---

migrator.go

- [] Tested
ref https://github.com/go-gorm/gorm/pull/4980/

feat: get column types by ordinal position order

---

migrator.go

https://github.com/go-sql-driver/mysql/issues/1213#issuecomment-843550804
Fix migrator issue in a transaction

fix migrator in transaction

---

mysql.go

Use WriteByte in case of single byte writing

---

.gitignore
go.sum
migrator.go

feat: implement get index

---

migrator.go

fix(Migrator): GetIndexes query should use table name

---

go.mod
go.sum

feat: upgrade gorm

---

migrator.go

feat: shard db & not shard tabel

---

migrator.go

feat: CurrentSchema

---

migrator.go

related to https://github.com/go-gorm/gorm/pull/5627

feat: support type alias

---

mysql.go

hello:
when the gorm debug sql,the time type display require a optimize.
when open a mysql connection with param "loc=Local".
And then execute sql，if set the time.Time utc,like this
`
t := time.Now()
t = t.UTC()
err = db.Table("test").Where("created_at>?", t).Find(&result).Error
`
the debug will show this
`
SELECT * FROM `test` WHERE created_at>'2022-10-12 15:02:46.587'
`
but check the mysql general log,it exec this sql
`
SELECT * FROM `test` WHERE created_at>'2022-10-12 23:02:46.5873415'
`
so if set the param “loc=Local”，when debug a sql，time zones also need to be considered,
Otherwise the print and the actual execution will be inconsistent and misleading.

opt time value display the debug sql

---

mysql.go

fix https://github.com/go-gorm/gorm/issues/6072

remove redundant `NOT NULL`

---

error_translator.go
go.mod
go.sum

This PR adds support for translating MySql errors like unique key violation to native gorm errors (ErrDuplicatedKey)
Related PR in gorm repo: https://github.com/go-gorm/gorm/pull/6004

feat: error translator support added

---

mysql.go
mysql_test.go

feat: when dsn config is nil  mysql.parseDSN

---

go.mod
go.sum
migrator.go

migrator support table comment.
1. [https://github.com/go-gorm/gorm/pull/6225](https://github.com/go-gorm/gorm/pull/6225)
2. [https://github.com/go-gorm/mysql/pull/114](https://github.com/go-gorm/mysql/pull/114)
3. [https://github.com/go-gorm/gen/pull/822](https://github.com/go-gorm/gen/pull/822)

feat: migrator support table comment

---

migrator.go

feat: index sort by name

---

.github/workflows/tests.yml

We don't have any pipeline job to check if the project can run the build and successfully run the tests after any commit. We need to be sure that every commit is buildable and passes the tests.

ci: added build & test jobs

---

migrator.go

Fix TiDB minor and patch version in error log

fix: tidb error log

---

.github/workflows/tests.yml

update go testing versions to be consistent with gorm
It blocks other mr, such as #123

ci: update go testing versions

---

migrator.go

make sure that default value like: _utf8mb4\'D\' , single quote wouldn't be trimed

only trim paired single-quotes for column.DefaultValue

---

go.mod
go.sum

1. Updated the go version to 1.18 which is aligned with [gorm.io/gorm](https://github.com/go-gorm/gorm/blob/0daaf1747cfa4e4850376ad50a7834fb78b0cc0e/go.mod#L3) in the go.mod.
2. Updated the dependency gorm.io/gorm from v1.25.7 to v1.25.11.
3. Updated the dependency github.com/go-sql-driver/mysql from v1.7.0 to v1.8.1.

Updated the go version to 1.18.
